# Generated by Django 2.2.7 on 2019-12-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order_quantity',
        ),
    ]
